use_frameworks!

source 'http://git.dev.qianmi.com/adminapp/qmspec-ios.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
target '${POD_NAME}_Example' do
  pod '${POD_NAME}', :path => '../'

  pod 'QMTheme'
    pod 'QMNavigator'
    
    # Your 'node_modules' directory is probably in the root of your project,
    # but if not, adjust the `:path` accordingly
    pod 'React', :path => '../../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTWebSocket', # needed for debugging
    'RCTNetwork',
    'RCTImage'
    # Add any other subspecs you want to use in your project
    ]

  target '${POD_NAME}_Tests' do
    inherit! :search_paths

    ${INCLUDED_PODS}
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
