use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'http://git.dev.qianmi.com/adminapp/qmspec-ios.git'

platform :ios, '9.0'
target '${POD_NAME}_Example' do
  pod '${POD_NAME}', :path => '../'

  pod 'QMTargetRequest'
  pod 'QMNavigator'

  target '${POD_NAME}_Tests' do
    inherit! :search_paths

    ${INCLUDED_PODS}
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
